// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.zzl.mynote.domain;

import com.zzl.mynote.domain.Artical;
import com.zzl.mynote.domain.ArticalDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ArticalDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ArticalDataOnDemand: @Component;
    
    private Random ArticalDataOnDemand.rnd = new SecureRandom();
    
    private List<Artical> ArticalDataOnDemand.data;
    
    public Artical ArticalDataOnDemand.getNewTransientArtical(int index) {
        Artical obj = new Artical();
        setContent(obj, index);
        return obj;
    }
    
    public void ArticalDataOnDemand.setContent(Artical obj, int index) {
        String content = "content_" + index;
        obj.setContent(content);
    }
    
    public Artical ArticalDataOnDemand.getSpecificArtical(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Artical obj = data.get(index);
        Long id = obj.getId();
        return Artical.findArtical(id);
    }
    
    public Artical ArticalDataOnDemand.getRandomArtical() {
        init();
        Artical obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Artical.findArtical(id);
    }
    
    public boolean ArticalDataOnDemand.modifyArtical(Artical obj) {
        return false;
    }
    
    public void ArticalDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Artical.findArticalEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Artical' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Artical>();
        for (int i = 0; i < 10; i++) {
            Artical obj = getNewTransientArtical(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
