// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.zzl.mynote.domain;

import com.zzl.mynote.domain.ArticleTypeDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ArticleTypeDataOnDemand_Roo_Configurable {
    
    declare @type: ArticleTypeDataOnDemand: @Configurable;
    
}
