// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.zzl.mynote.domain;

import com.zzl.mynote.domain.ArticalType;
import com.zzl.mynote.domain.ArticalTypeDataOnDemand;
import com.zzl.mynote.domain.ArticalTypeIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ArticalTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ArticalTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ArticalTypeIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ArticalTypeIntegrationTest: @Transactional;
    
    @Autowired
    ArticalTypeDataOnDemand ArticalTypeIntegrationTest.dod;
    
    @Test
    public void ArticalTypeIntegrationTest.testCountArticalTypes() {
        Assert.assertNotNull("Data on demand for 'ArticalType' failed to initialize correctly", dod.getRandomArticalType());
        long count = ArticalType.countArticalTypes();
        Assert.assertTrue("Counter for 'ArticalType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ArticalTypeIntegrationTest.testFindArticalType() {
        ArticalType obj = dod.getRandomArticalType();
        Assert.assertNotNull("Data on demand for 'ArticalType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ArticalType' failed to provide an identifier", id);
        obj = ArticalType.findArticalType(id);
        Assert.assertNotNull("Find method for 'ArticalType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ArticalType' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ArticalTypeIntegrationTest.testFindAllArticalTypes() {
        Assert.assertNotNull("Data on demand for 'ArticalType' failed to initialize correctly", dod.getRandomArticalType());
        long count = ArticalType.countArticalTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'ArticalType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ArticalType> result = ArticalType.findAllArticalTypes();
        Assert.assertNotNull("Find all method for 'ArticalType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ArticalType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ArticalTypeIntegrationTest.testFindArticalTypeEntries() {
        Assert.assertNotNull("Data on demand for 'ArticalType' failed to initialize correctly", dod.getRandomArticalType());
        long count = ArticalType.countArticalTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ArticalType> result = ArticalType.findArticalTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ArticalType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ArticalType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ArticalTypeIntegrationTest.testFlush() {
        ArticalType obj = dod.getRandomArticalType();
        Assert.assertNotNull("Data on demand for 'ArticalType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ArticalType' failed to provide an identifier", id);
        obj = ArticalType.findArticalType(id);
        Assert.assertNotNull("Find method for 'ArticalType' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyArticalType(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ArticalType' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ArticalTypeIntegrationTest.testMergeUpdate() {
        ArticalType obj = dod.getRandomArticalType();
        Assert.assertNotNull("Data on demand for 'ArticalType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ArticalType' failed to provide an identifier", id);
        obj = ArticalType.findArticalType(id);
        boolean modified =  dod.modifyArticalType(obj);
        Integer currentVersion = obj.getVersion();
        ArticalType merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ArticalType' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ArticalTypeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ArticalType' failed to initialize correctly", dod.getRandomArticalType());
        ArticalType obj = dod.getNewTransientArticalType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ArticalType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ArticalType' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'ArticalType' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ArticalTypeIntegrationTest.testRemove() {
        ArticalType obj = dod.getRandomArticalType();
        Assert.assertNotNull("Data on demand for 'ArticalType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ArticalType' failed to provide an identifier", id);
        obj = ArticalType.findArticalType(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ArticalType' with identifier '" + id + "'", ArticalType.findArticalType(id));
    }
    
}
