// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.zzl.mynote.domain;

import com.zzl.mynote.domain.ArticleType;
import com.zzl.mynote.domain.ArticleTypeDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ArticleTypeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ArticleTypeDataOnDemand: @Component;
    
    private Random ArticleTypeDataOnDemand.rnd = new SecureRandom();
    
    private List<ArticleType> ArticleTypeDataOnDemand.data;
    
    public ArticleType ArticleTypeDataOnDemand.getNewTransientArticleType(int index) {
        ArticleType obj = new ArticleType();
        setName(obj, index);
        return obj;
    }
    
    public void ArticleTypeDataOnDemand.setName(ArticleType obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public ArticleType ArticleTypeDataOnDemand.getSpecificArticleType(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ArticleType obj = data.get(index);
        Long id = obj.getId();
        return ArticleType.findArticleType(id);
    }
    
    public ArticleType ArticleTypeDataOnDemand.getRandomArticleType() {
        init();
        ArticleType obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ArticleType.findArticleType(id);
    }
    
    public boolean ArticleTypeDataOnDemand.modifyArticleType(ArticleType obj) {
        return false;
    }
    
    public void ArticleTypeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ArticleType.findArticleTypeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ArticleType' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ArticleType>();
        for (int i = 0; i < 10; i++) {
            ArticleType obj = getNewTransientArticleType(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
