// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.zzl.mynote.domain;

import com.zzl.mynote.domain.ArticalType;
import com.zzl.mynote.domain.ArticalTypeDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ArticalTypeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ArticalTypeDataOnDemand: @Component;
    
    private Random ArticalTypeDataOnDemand.rnd = new SecureRandom();
    
    private List<ArticalType> ArticalTypeDataOnDemand.data;
    
    public ArticalType ArticalTypeDataOnDemand.getNewTransientArticalType(int index) {
        ArticalType obj = new ArticalType();
        setName(obj, index);
        return obj;
    }
    
    public void ArticalTypeDataOnDemand.setName(ArticalType obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public ArticalType ArticalTypeDataOnDemand.getSpecificArticalType(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ArticalType obj = data.get(index);
        Long id = obj.getId();
        return ArticalType.findArticalType(id);
    }
    
    public ArticalType ArticalTypeDataOnDemand.getRandomArticalType() {
        init();
        ArticalType obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ArticalType.findArticalType(id);
    }
    
    public boolean ArticalTypeDataOnDemand.modifyArticalType(ArticalType obj) {
        return false;
    }
    
    public void ArticalTypeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ArticalType.findArticalTypeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ArticalType' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ArticalType>();
        for (int i = 0; i < 10; i++) {
            ArticalType obj = getNewTransientArticalType(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
