// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.zzl.mynote.domain;

import com.zzl.mynote.domain.Artical;

privileged aspect Artical_Roo_JavaBean {
    
    public String Artical.getContent() {
        return this.content;
    }
    
    public void Artical.setContent(String content) {
        this.content = content;
    }
    
}
